# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 28 Nov 2011 10:46:11 +0000
*               @ALL          1
*               @user         8
