<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: root
 * Date: Mon, 28 Nov 2011 20:56:15 +0800
 */

$conf['title'] = '玟唐传播';
$conf['lang'] = 'zh';
$conf['template'] = 'guu';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['gdlib'] = '0';

// end auto-generated content
